# Site settings
title: Anish M.S. Shrestha
email: anish.ms.shrestha--at--gmail--dot--com
description: > # this means to ignore newlines until "baseurl:"
  Anish M.S. Shrestha. Bioinformatics. DLSU-Manila
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: anishmss
github_username:  anishmss

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
#job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
